export const projects = [
  {
    title: 'Music Site',
    description: "Project Built Using VueJS to represent African Music",
      image: '/images/music site.png',
      tags: ['VueJS', 'JavaScript'],
    visit: 'https://github.com/Olive-Spider/music-site',
    source: 'https://oes-music.netlify.app/',
    id: 0,
  },
  {
    title: 'Gericht Restaurant',
    description: "Project Built Using ReactJS To Create A Modern UI/UX Restaurant Landing Page Website",
      image: '/images/1.png',
      tags: ['React', 'JavaScript'],
    visit: 'https://github.com/Olive-Spider/mock-restaurant',
    source: 'https://mock-restaurant-delta.vercel.app/',
    id: 1,
  },
  {
    title: 'Stripe Mockup',
    description:"Web Application Inspired By Stripe's Unique and Modern UI/UX Design.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    visit: 'https://github.com/Olive-Spider/stripe-ish',
    source: 'https://stripe-ish.netlify.app/',
    id: 2,
  },
  {
    title: 'Hoo Bank',
    description: "A Fully Responsive Bank Website with Modern UI/UX using React JS and Tailwind CSS.",
      image: '/images/3.png',
      tags: ['ReactJS', 'TailwindCSS'],
    visit: 'https://github.com/Olive-Spider/mock-bank',
    source: 'https://mock-bank-alpha.vercel.app/',
    id: 3,
  },
  {
    title: 'YouTube Clone',
    description: "A Twist On YouTube's UI/UX Using ReactJS and RapidAPI To Generate Real YouTube Videos",
    image: '/images/4.png',
    tags: ['ReactJS', 'Material UI', 'RapidAPI'],
    visit: 'https://github.com/Olive-Spider/youtube-clone',
    source: 'https://youtube-clone-sooty-five.vercel.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2022, text: 'Started my journey', },
  { year: 2023, text: ['Building projects to sharpen my developer skills', 'Shared my projects with the world', 'Landed my first Software Developer job',]},
  // { year: 2019, text: 'Founded JavaScript Mastery', },
  // { year: 2020, text: 'Shared my projects with the world', },
  // { year: 2021, text: 'Started my own platform', },
];